#!/bin/bash

#===[ Code ]===#
mkdir -p "/lib/modules/$(uname -r)"
mkdir -p "/lib/modules/$(uname -r)/kernel/drivers/net/wireless/"
mkdir -p /usr/src/

mv /kernel-headers/modules.* "/lib/modules/$(uname -r)"
mv /kernel-headers "/usr/src/$(uname -r)"
cd "/lib/modules/$(uname -r)"
ln -sfnv "/usr/src/$(uname -r)" build
cd

echo ""
echo "Installation completed. Good luck )"
echo ""
echo "By Anonym3310"
echo ""
